# Use a imagem oficial do Python
FROM python:3.9

# Crie o diretório de trabalho
WORKDIR /app

# Copie o arquivo requirements.txt para o diretório de trabalho
COPY requirements.txt .

# Instale as dependências
RUN pip install -r requirements.txt

# Copie o código da aplicação para o diretório de trabalho
COPY . .

# Configure a porta exposta
EXPOSE 5000

# Defina o comando a ser executado quando o container for iniciado
CMD [ "python", "app.py" ]